{% set name = "python-benedict" %}
{% set version = "0.25.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-benedict-{{ version }}.tar.gz
  sha256: 9e25e7d4de2d5f8a9c20c74a764d29933bcf5100c1e051c5a9d1418de66a7d0f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - ftfy >=6.0.0,<7.0.0
    - mailchecker >=4.1.0,<5.0.0
    - phonenumbers >=8.12.0,<9.0.0
    - python >=3.6
    - python-dateutil >=2.8.0,<3.0.0
    - python-fsutil >=0.6.0,<1.0.0
    - python-slugify >=6.0.1,<7.0.0
    - pyyaml >=6.0,<7.0
    - requests >=2.26.0,<3.0.0
    - toml >=0.10.2,<1.0.0
    - xmltodict >=0.12.0,<1.0.0

test:
  imports:
    - benedict
    - benedict.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fabiocaccamo/python-benedict
  summary: python-benedict is a dict subclass with keylist/keypath support, I/O shortcuts (base64, csv, json, pickle, plist, query-string, toml, xml, yaml) and many utilities... for humans, obviously.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
    - fabiocaccamo
